version: '3'
services:  
  database:
    container_name: baraholka-database
    image: postgres:14.1-alpine
    restart: always
    networks:
      - baraholka-network
    environment:
      POSTGRES_DB: ${POSTGRE_DB_NAME}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgres
  
  backend:
    container_name: baraholka-backend
    build: 
      context: ../Backend
    restart: always
    networks:
      - baraholka-network
    ports:
      - 8080:8080
    environment:
      - "PYTHONUNBUFFERED=1"
    env_file:
      - ".env"
    command: ["gunicorn", "--preload", "-w", "1", "-k", "uvicorn.workers.UvicornWorker", "--timeout", "600", "-b", "0.0.0.0:8080", "main:app"]
    depends_on:
      - database

  frontend:
    container_name: baraholka-frontend
    image: darkartheme/baraholka-frontend:0.3.3-react-only
    networks:
      - baraholka-network
    volumes:
      - react_build:/react/build
    depends_on:
      - database
      - backend

  nginx:
    container_name: baraholka-nginx
    image: nginx:1.21-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - react_build:/var/www/react
    depends_on:
      - database
      - backend
      - frontend
    networks:
      - baraholka-network

volumes:
  postgres_data:
  react_build:

networks:
  baraholka-network: