version: '3'
services:  
  database:
    container_name: baraholka-database
    image: postgres:14.1-alpine
    restart: always
    networks:
      - baraholka-network
    environment:
      POSTGRES_DB: ${POSTGRE_DB_NAME}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgres
  
  backend:
    container_name: baraholka-backend
    image: darkartheme/baraholka-backend:0.4.4
    restart: always
    networks:
      - baraholka-network
    # ports:
    #   - 8080:8080
    environment:
      - "PYTHONUNBUFFERED=1"
    env_file:
      - ".env"
    command: ["gunicorn", "--preload", "-w", "1", "-k", "uvicorn.workers.UvicornWorker", "--timeout", "600", "-b", "0.0.0.0:8080", "main:app"]
    depends_on:
      - database

  frontend:
    container_name: baraholka-frontend
    image: darkartheme/baraholka-frontend:0.5.1
    networks:
      - baraholka-network
    # restart: always
    volumes:
      - react_build:/react/build
    depends_on:
      - database
      - backend

  nginx:
    container_name: baraholka-nginx
    image: nginx:1.21-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./601345-darkartheme-tmweb-ru:/etc/nginx/sites-available/tmweb.ru
      # - ./misis-marketplace-ru:/etc/nginx/sites-available/misis-marketplace.ru
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tm-web-fullchain.pem:/etc/letsencrypt/live/601345-darkartheme.tmweb.ru/fullchain.pem:ro
      - ./tm-web-privkey.pem:/etc/letsencrypt/live/601345-darkartheme.tmweb.ru/privkey.pem:ro
      - ./mm-fullchain.pem:/etc/letsencrypt/live/misis-marketplace.ru/fullchain.pem:ro
      - ./mm-privkey.pem:/etc/letsencrypt/live/misis-marketplace.ru/privkey.pem:ro
      - ./options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      - react_build:/var/www/react
    # command: 
    #   - mkdir /etc/nginx/sites-enabled
    #   - ln -s /etc/nginx/sites-available/tmweb.ru /etc/nginx/sites-enabled/tmweb.ru
    #   - ln -s /etc/nginx/sites-available/misis-marketplace.ru /etc/nginx/sites-enabled/misis-marketplace.ru
    depends_on:
      - database
      - backend
      - frontend
    networks:
      - baraholka-network
    # network_mode: host

volumes:
  postgres_data:
  react_build:

networks:
  baraholka-network: