version: '3'
services:
  db:
    container_name: postgres_14
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgres