version: '3'
services:
  backend:
    build: .
    restart: always
    ports:
      - "3002:3002"
    environment:
      - "PYTHONUNBUFFERED=1"
    env_file:
      - ".env"
    command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:3002", "main:app"]